title: Emmanuel Randle
description: >
  Doctoral researcher in earthquake and tsunami risk, uncertainty and correlation,
  damage and population consequences, and catastrophe risk for insurance and reinsurance.
url: "https://natcatanalystrandle.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
exclude:
  - README.md
